const API = "https://api.cedarmc.org";
const $ = id => document.getElementById(id);
const els = {
  loginScreen:$('loginScreen'), app:$('app'), loginBtn:$('loginBtn'), loginMessage:$('loginMessage'),
  profileBtn:$('profileBtn'), profileAvatar:$('profileAvatar'), profileName:$('profileName'), profileRole:$('profileRole'), profileMenu:$('profileMenu'), menuName:$('menuName'), menuUsername:$('menuUsername'), logoutBtn:$('logoutBtn'),
  title:$('title'), description:$('description'), footer:$('footer'), color:$('color'), colorPicker:$('colorPicker'), imageEnabled:$('imageEnabled'),
  ticketTypesEditor:$('ticketTypesEditor'), transcriptChannel:$('transcriptChannel'), pingRole:$('pingRole'), pingStaffOnCreate:$('pingStaffOnCreate'), staffRoleGrid:$('staffRoleGrid'), bypassRoleGrid:$('bypassRoleGrid'),
  claimEnabled:$('claimEnabled'), lockToClaimer:$('lockToClaimer'), allowUnclaim:$('allowUnclaim'), allowTransfer:$('allowTransfer'), showClaimer:$('showClaimer'), claimLabel:$('claimLabel'), unclaimLabel:$('unclaimLabel'), transferLabel:$('transferLabel'),
  defaultPriority:$('defaultPriority'), autoCloseEnabled:$('autoCloseEnabled'), autoCloseHours:$('autoCloseHours'),
  ownerAddMembers:$('ownerAddMembers'), ownerRemoveMembers:$('ownerRemoveMembers'), ownerRename:$('ownerRename'), ownerRequestClose:$('ownerRequestClose'), ownerCloseDirectly:$('ownerCloseDirectly'),
  channelSelect:$('channelSelect'), saveBtn:$('saveBtn'), sendBtn:$('sendBtn'), statusMessage:$('statusMessage'),
  previewEmbed:$('previewEmbed'), previewTitle:$('previewTitle'), previewDescription:$('previewDescription'), previewImage:$('previewImage'), previewFooter:$('previewFooter'), previewButtons:$('previewButtons'), claimPreviewLabel:$('claimPreviewLabel'),
  ticketsView:$('ticketsView'), activeView:$('activeView'), activeNav:$('activeNav'), activeCount:$('activeCount'), refreshTicketsBtn:$('refreshTicketsBtn'), activeTicketsList:$('activeTicketsList'), activeStatus:$('activeStatus'), ticketSearch:$('ticketSearch'), ticketFilter:$('ticketFilter'), workloadList:$('workloadList'), auditView:$('auditView'), auditNav:$('auditNav'), auditList:$('auditList'), refreshAuditBtn:$('refreshAuditBtn')
};
let state={config:null,channels:[],roles:[],categories:[]};

function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function request(path,options={}){return fetch(API+path,{credentials:'include',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});}
function status(text,type=''){els.statusMessage.textContent=text;els.statusMessage.className='status-message '+type;}
function setProfile(user){els.profileAvatar.src=user.avatarUrl||'';els.profileName.textContent=user.displayName||user.username;els.profileRole.textContent=user.permissions?.guildOwner?'Server Owner':(user.roles?.[0]||'CedarMC Staff');els.menuName.textContent=user.displayName||user.username;els.menuUsername.textContent='@'+user.username;}
function selectOptions(items,current,blank='Choose…'){return `<option value="">${escapeHtml(blank)}</option>`+items.map(x=>`<option value="${x.id}" ${x.id===current?'selected':''}>${escapeHtml(x.name)}</option>`).join('');}
function selectedRoleIds(container){return [...container.querySelectorAll('input[type=checkbox]:checked')].map(x=>x.value);}
function renderRoleGrid(container,selected=[]){container.innerHTML=state.roles.map(role=>`<label class="role-check"><input type="checkbox" value="${role.id}" ${selected.includes(role.id)?'checked':''}><span class="role-dot" style="--role:${role.color||'#777'}"></span><span>${escapeHtml(role.name)}</span></label>`).join('');}
function renderTicketTypes(){
  els.ticketTypesEditor.innerHTML=state.config.buttons.map((b,i)=>`<div class="type-card" data-index="${i}"><div class="type-head"><strong>${escapeHtml(b.typeName||b.label)}</strong><span>${escapeHtml(b.id)}</span></div><div class="type-grid"><label>Button label<input class="type-label" maxlength="80" value="${escapeHtml(b.label)}"></label><label>Ticket name<input class="type-name" maxlength="80" value="${escapeHtml(b.typeName||b.label)}"></label><label>Button color<select class="type-style">${['Primary','Secondary','Success','Danger'].map(s=>`<option ${s===b.style?'selected':''}>${s}</option>`).join('')}</select></label><label>Discord category<select class="type-category">${selectOptions(state.categories,b.categoryId,'Choose category…')}</select></label></div></div>`).join('');
  els.ticketTypesEditor.querySelectorAll('input,select').forEach(x=>x.addEventListener('input',renderPreview));
}
function renderPreview(){
  els.previewTitle.textContent=els.title.value||'CEDARMC SUPPORT';els.previewDescription.innerHTML=escapeHtml(els.description.value).replace(/\n/g,'<br>');els.previewFooter.textContent=els.footer.value;els.previewImage.style.display=els.imageEnabled.checked?'grid':'none';
  if(/^#[0-9a-f]{6}$/i.test(els.color.value.trim())){els.previewEmbed.style.borderLeftColor=els.color.value.trim();els.colorPicker.value=els.color.value.trim();}
  const buttons=[...els.ticketTypesEditor.querySelectorAll('.type-card')].map(card=>({label:card.querySelector('.type-label').value,style:card.querySelector('.type-style').value}));
  els.previewButtons.innerHTML=buttons.map(b=>`<span class="discord-button ${b.style.toLowerCase()}">${escapeHtml(b.label)}</span>`).join('');
  els.claimPreviewLabel.textContent='🎫 '+(els.claimLabel.value||'Claim Ticket');els.claimPreviewLabel.parentElement.style.opacity=els.claimEnabled.checked?'1':'.35';
}
function fillForm(config){
  state.config=config;els.title.value=config.title;els.description.value=config.description;els.footer.value=config.footer;els.color.value=config.color;els.colorPicker.value=config.color;els.imageEnabled.checked=config.imageEnabled!==false;
  const st=config.settings||{},cl=st.claim||{},p=st.permissions||{},m=st.management||{};
  els.transcriptChannel.innerHTML=selectOptions(state.channels,st.transcriptChannelId,'Choose transcript channel…');els.pingRole.innerHTML=selectOptions(state.roles,st.pingRoleId,'No role');els.pingStaffOnCreate.checked=st.pingStaffOnCreate!==false;
  renderRoleGrid(els.staffRoleGrid,st.staffRoleIds||[]);renderRoleGrid(els.bypassRoleGrid,st.bypassRoleIds||[]);
  els.claimEnabled.checked=cl.enabled!==false;els.lockToClaimer.checked=cl.lockToClaimer!==false;els.allowUnclaim.checked=cl.allowUnclaim!==false;els.allowTransfer.checked=cl.allowTransfer!==false;els.showClaimer.checked=cl.showClaimer!==false;els.claimLabel.value=cl.claimLabel||'Claim Ticket';els.unclaimLabel.value=cl.unclaimLabel||'Unclaim';els.transferLabel.value=cl.transferLabel||'Transfer Claim';els.defaultPriority.value=m.defaultPriority||'normal';els.autoCloseEnabled.checked=m.autoCloseEnabled===true;els.autoCloseHours.value=Number(m.autoCloseHours)||72;
  els.ownerAddMembers.checked=p.ownerAddMembers!==false;els.ownerRemoveMembers.checked=p.ownerRemoveMembers!==false;els.ownerRename.checked=p.ownerRename!==false;els.ownerRequestClose.checked=p.ownerRequestClose!==false;els.ownerCloseDirectly.checked=p.ownerCloseDirectly===true;
  renderTicketTypes();renderPreview();
}
function getConfig(){
  const buttons=[...els.ticketTypesEditor.querySelectorAll('.type-card')].map((card,i)=>({id:state.config.buttons[i].id,label:card.querySelector('.type-label').value.trim(),typeName:card.querySelector('.type-name').value.trim(),style:card.querySelector('.type-style').value,categoryId:card.querySelector('.type-category').value}));
  return {title:els.title.value.trim(),description:els.description.value,footer:els.footer.value.trim(),color:els.color.value.trim(),imageEnabled:els.imageEnabled.checked,buttons,settings:{transcriptChannelId:els.transcriptChannel.value,staffRoleIds:selectedRoleIds(els.staffRoleGrid),pingRoleId:els.pingRole.value,bypassRoleIds:selectedRoleIds(els.bypassRoleGrid),pingStaffOnCreate:els.pingStaffOnCreate.checked,claim:{enabled:els.claimEnabled.checked,lockToClaimer:els.lockToClaimer.checked,allowUnclaim:els.allowUnclaim.checked,allowTransfer:els.allowTransfer.checked,showClaimer:els.showClaimer.checked,claimLabel:els.claimLabel.value.trim(),unclaimLabel:els.unclaimLabel.value.trim(),transferLabel:els.transferLabel.value.trim()},permissions:{ownerAddMembers:els.ownerAddMembers.checked,ownerRemoveMembers:els.ownerRemoveMembers.checked,ownerRename:els.ownerRename.checked,ownerRequestClose:els.ownerRequestClose.checked,ownerCloseDirectly:els.ownerCloseDirectly.checked},management:{defaultPriority:els.defaultPriority.value||'normal',autoCloseEnabled:els.autoCloseEnabled.checked,autoCloseHours:Math.min(Math.max(Number(els.autoCloseHours.value)||72,1),720)}}};
}
async function loadAll(){
  const [cfgRes,chRes,roleRes,catRes]=await Promise.all([request('/api/tickets/config'),request('/api/discord/channels'),request('/api/discord/roles'),request('/api/discord/categories')]);
  if(!cfgRes.ok)throw new Error('Could not load ticket settings.');
  state.channels=chRes.ok?await chRes.json():[];state.roles=roleRes.ok?await roleRes.json():[];state.categories=catRes.ok?await catRes.json():[];
  els.channelSelect.innerHTML=selectOptions(state.channels,'','Choose a channel…');fillForm(await cfgRes.json());
}
async function initAuth(){
  const params=new URLSearchParams(location.search),auth=params.get('auth'),reason=params.get('reason');if(auth){history.replaceState({},'',location.pathname+location.hash);if(auth==='denied')els.loginMessage.textContent=reason||'Your Discord account does not have dashboard access.';else if(auth==='failed')els.loginMessage.textContent='Discord login failed. Please try again.';}
  try{const res=await request('/api/auth/me');if(!res.ok)throw new Error('auth');const data=await res.json();setProfile(data.user);els.loginScreen.classList.add('hidden');els.app.classList.remove('hidden');try{await loadAll();}catch(e){status('Could not load your saved ticket settings: '+e.message+' — Save is disabled to protect your config.','error');els.saveBtn.disabled=true;els.sendBtn.disabled=true;}}catch{els.loginScreen.classList.remove('hidden');els.app.classList.add('hidden');}
}

let activeTickets=[];
function fmtStatus(s){return String(s||'open').replaceAll('-',' ').replace(/\b\w/g,c=>c.toUpperCase())}
function renderWorkload(items){const map=new Map();for(const t of items){if(!t.claimedBy)continue;const id=t.claimedBy.id||t.claimedById,name=t.claimedBy.displayName||t.claimedBy.username||'Staff';if(!id)continue;const x=map.get(id)||{name,open:0,urgent:0,waiting:0};x.open++;if(t.priority==='urgent')x.urgent++;if(String(t.status||'').startsWith('waiting-'))x.waiting++;map.set(id,x)}const rows=[...map.values()].sort((a,b)=>b.open-a.open);els.workloadList.innerHTML=rows.length?rows.map(x=>`<div class="workload-item"><strong>${escapeHtml(x.name)}</strong><span>${x.open} open · ${x.urgent} urgent · ${x.waiting} waiting</span></div>`).join(''):'<div class="empty-state">No claimed tickets yet.</div>'}
function renderActive(){const q=(els.ticketSearch.value||'').toLowerCase(),f=els.ticketFilter.value;let items=activeTickets.filter(t=>{const hay=[t.name,t.owner?.displayName,t.owner?.username,t.claimedBy?.displayName,t.claimedBy?.username].filter(Boolean).join(' ').toLowerCase();if(q&&!hay.includes(q))return false;if(f==='claimed'&&!t.claimedBy)return false;if(f==='unclaimed'&&t.claimedBy)return false;if(f==='urgent'&&t.priority!=='urgent')return false;if(f==='waiting-user'&&t.status!=='waiting-user')return false;if(f==='waiting-staff'&&t.status!=='waiting-staff')return false;return true});renderWorkload(activeTickets);els.activeCount.textContent=activeTickets.length;els.activeTicketsList.innerHTML=items.length?items.map(t=>`<div class="ticket-card"><div class="ticket-main"><div class="ticket-head"><strong>#${escapeHtml(t.name||'ticket')}</strong><span class="status-pill ${t.claimedBy?'claimed':'unclaimed'}">${t.claimedBy?'Claimed':'Unclaimed'}</span><span class="priority-pill priority-${escapeHtml(t.priority||'normal')}">${fmtStatus(t.priority||'normal')}</span><span class="waiting-pill">${fmtStatus(t.status||'open')}</span></div><div class="ticket-meta"><span>Owner: ${escapeHtml(t.owner?.displayName||t.owner?.username||'Unknown')}</span><span>Claimed by: ${escapeHtml(t.claimedBy?.displayName||t.claimedBy?.username||'Nobody')}</span></div></div><div class="ticket-actions"><select class="priority-select" data-id="${t.id}"><option value="low" ${t.priority==='low'?'selected':''}>Low</option><option value="normal" ${t.priority==='normal'?'selected':''}>Normal</option><option value="high" ${t.priority==='high'?'selected':''}>High</option><option value="urgent" ${t.priority==='urgent'?'selected':''}>Urgent</option></select><select class="status-select" data-id="${t.id}"><option value="open" ${t.status==='open'?'selected':''}>Open</option><option value="waiting-user" ${t.status==='waiting-user'?'selected':''}>Waiting on User</option><option value="waiting-staff" ${t.status==='waiting-staff'?'selected':''}>Waiting on Staff</option></select>${t.url?`<a class="secondary" href="${escapeHtml(t.url)}" target="_blank">Open Discord</a>`:''}</div></div>`).join(''):'<div class="empty-state">No tickets match this view.</div>';document.querySelectorAll('.priority-select').forEach(x=>x.onchange=()=>updateTicket(x.dataset.id,{priority:x.value}));document.querySelectorAll('.status-select').forEach(x=>x.onchange=()=>updateTicket(x.dataset.id,{status:x.value}))}
async function loadActive(){els.activeStatus.textContent='Loading active tickets…';const r=await request('/api/tickets/active');if(!r.ok){els.activeStatus.textContent='Could not load active tickets.';return}const d=await r.json();activeTickets=Array.isArray(d)?d:(d.tickets||[]);renderActive();els.activeStatus.textContent=''}
async function updateTicket(id,body){const r=await request('/api/tickets/'+encodeURIComponent(id)+'/manage',{method:'POST',body:JSON.stringify(body)});if(!r.ok){els.activeStatus.textContent='Could not update ticket.';return}await loadActive()}

async function loadAudit(){els.auditList.innerHTML='<div class="audit-empty">Loading audit log…</div>';const res=await request('/api/audit?limit=75');if(!res.ok){els.auditList.innerHTML='<div class="audit-empty">Could not load audit log.</div>';return;}const entries=await res.json();els.auditList.innerHTML=entries.length?entries.map(e=>`<div class="audit-row">${e.actor?.avatarUrl?`<img src="${escapeHtml(e.actor.avatarUrl)}">`:'<div class="audit-avatar-fallback">▲</div>'}<div><strong>${escapeHtml(e.actor?.displayName||e.actor?.username||'System')}</strong><span>${escapeHtml(e.action)}</span><small>${escapeHtml(new Date(e.timestamp).toLocaleString())}</small></div></div>`).join(''):'<div class="audit-empty">No dashboard actions logged yet.</div>';}

['input','change'].forEach(ev=>[els.title,els.description,els.footer,els.color,els.imageEnabled,els.claimEnabled,els.claimLabel].forEach(el=>el.addEventListener(ev,renderPreview)));
els.colorPicker.addEventListener('input',()=>{els.color.value=els.colorPicker.value.toUpperCase();renderPreview();});
els.loginBtn.addEventListener('click',()=>location.href=API+'/auth/discord/login');els.profileBtn.addEventListener('click',()=>els.profileMenu.classList.toggle('hidden'));document.addEventListener('click',e=>{if(!e.target.closest('.profile-wrap'))els.profileMenu.classList.add('hidden');});els.logoutBtn.addEventListener('click',async()=>{await request('/auth/logout',{method:'POST',body:'{}'}).catch(()=>{});location.reload();});
function showView(v){document.querySelectorAll('.nav-link').forEach(x=>x.classList.remove('active'));els.ticketsView.classList.add('hidden');els.activeView.classList.add('hidden');els.auditView.classList.add('hidden');if(v==='active'){els.activeNav.classList.add('active');els.activeView.classList.remove('hidden');loadActive()}else if(v==='audit'){els.auditNav.classList.add('active');els.auditView.classList.remove('hidden');loadAudit()}else{document.querySelector('a[href="#tickets"]').classList.add('active');els.ticketsView.classList.remove('hidden')}}els.auditNav.addEventListener('click',e=>{e.preventDefault();showView('audit')});els.activeNav.addEventListener('click',e=>{e.preventDefault();showView('active')});document.querySelector('a[href="#tickets"]').addEventListener('click',e=>{e.preventDefault();showView('tickets')});els.refreshAuditBtn.addEventListener('click',loadAudit);els.refreshTicketsBtn.addEventListener('click',loadActive);els.ticketSearch.addEventListener('input',renderActive);els.ticketFilter.addEventListener('change',renderActive);
els.saveBtn.addEventListener('click',async()=>{try{status('Saving full ticket system…');const res=await request('/api/tickets/config',{method:'POST',body:JSON.stringify(getConfig())});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||`HTTP ${res.status}`);state.config=data;status('Ticket system saved. New tickets use these settings immediately.','ok');}catch(err){status('Save failed: '+err.message,'error');}});
els.sendBtn.addEventListener('click',async()=>{const channelId=els.channelSelect.value;if(!channelId){status('Choose the Discord channel first.','error');return;}try{status('Sending panel to Discord…');const res=await request('/api/tickets/send',{method:'POST',body:JSON.stringify({channelId})});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||`HTTP ${res.status}`);status('New ticket panel sent to Discord.','ok');}catch(err){status('Send failed: '+err.message,'error');}});
initAuth();
